name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "adopt"

      - name: Install dependencies
        run: |
          npm install
          cd android && chmod +x gradlew && ./gradlew dependencies

      - name: Build Android app
        run: |
          npm run build # Assuming this builds your Nuxt app
          npx cap sync android # Sync Capacitor and build the Android app
          cd android
          ./gradlew assembleRelease