name: Build

on:
    push:
        branches:
        - main
        paths-ignore:
          - '**.md'
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: npm run build