name: Deploy To ECS

on:
    push:
      branches:
        - deploy-ecr
    workflow_dispatch:

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: .

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: "us-east-1"

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push image to Amazon ECR
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: mello  # Replace with your ECR repository name
              IMAGE_TAG: latest  # Use the SHA hash as the image tag or change as necessary
            run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          - name: Output the image name
            run: |
              echo "ECR Registry URL: ${{ steps.login-ecr.outputs.registry }}"
