name: Op Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Job-level environment variables
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Install dependencies
        run: go install lesiw.io/op@latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run SSH command
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} 'echo "Hello, World!"'

      # - name: Run Go script
      #   run: op deploy
