name: Tofu Plan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  tofu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu plan
        run: |
          cd tofu
          tofu init
          tofu refresh
          tofu validate
          tofu plan
