name: Tofu

on:
    push:
      branches:
        - refactor-websocket-endpoint
    workflow_dispatch:

jobs:
  tofu:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1

      - name: Run Tofu
        run: |
          cd tofu
          tofu init
          tofu refresh
          tofu plan
